# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Iris Flower Classification 🌸

A simple machine-learning project using the classic Iris dataset.
The model predicts the type of iris flower based on measurements of petals and sepals.

## Technologies Used
- Python
- NumPy / Pandas
- Scikit-learn
- Random Forest Classifier

## How to Run
pip install -r requirements.txt
python train.py

## Accuracy
Approx. 95–98%

## Files
- train.py → Training script
- iris_model.pkl → Saved model (generated after running)
- scaler.pkl → Preprocessing scaler